//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAO.Blackjack.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAO.Blackjack.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_animal_pig {
            get {
                object obj = ResourceManager.GetObject("bg_animal_pig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_casino {
            get {
                object obj = ResourceManager.GetObject("bg_casino", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_default {
            get {
                object obj = ResourceManager.GetObject("bg_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_gentlemanly {
            get {
                object obj = ResourceManager.GetObject("bg_gentlemanly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_hacker {
            get {
                object obj = ResourceManager.GetObject("bg_hacker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_learning_center {
            get {
                object obj = ResourceManager.GetObject("bg_learning_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_living_room {
            get {
                object obj = ResourceManager.GetObject("bg_living_room", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_office {
            get {
                object obj = ResourceManager.GetObject("bg_office", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_shop {
            get {
                object obj = ResourceManager.GetObject("bg_shop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_zoo {
            get {
                object obj = ResourceManager.GetObject("bg_zoo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_1 {
            get {
                object obj = ResourceManager.GetObject("card_0_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_10 {
            get {
                object obj = ResourceManager.GetObject("card_0_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_11 {
            get {
                object obj = ResourceManager.GetObject("card_0_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_12 {
            get {
                object obj = ResourceManager.GetObject("card_0_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_13 {
            get {
                object obj = ResourceManager.GetObject("card_0_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_2 {
            get {
                object obj = ResourceManager.GetObject("card_0_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_3 {
            get {
                object obj = ResourceManager.GetObject("card_0_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_4 {
            get {
                object obj = ResourceManager.GetObject("card_0_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_5 {
            get {
                object obj = ResourceManager.GetObject("card_0_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_6 {
            get {
                object obj = ResourceManager.GetObject("card_0_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_7 {
            get {
                object obj = ResourceManager.GetObject("card_0_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_8 {
            get {
                object obj = ResourceManager.GetObject("card_0_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_0_9 {
            get {
                object obj = ResourceManager.GetObject("card_0_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_1 {
            get {
                object obj = ResourceManager.GetObject("card_1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_10 {
            get {
                object obj = ResourceManager.GetObject("card_1_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_11 {
            get {
                object obj = ResourceManager.GetObject("card_1_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_12 {
            get {
                object obj = ResourceManager.GetObject("card_1_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_13 {
            get {
                object obj = ResourceManager.GetObject("card_1_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_2 {
            get {
                object obj = ResourceManager.GetObject("card_1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_3 {
            get {
                object obj = ResourceManager.GetObject("card_1_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_4 {
            get {
                object obj = ResourceManager.GetObject("card_1_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_5 {
            get {
                object obj = ResourceManager.GetObject("card_1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_6 {
            get {
                object obj = ResourceManager.GetObject("card_1_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_7 {
            get {
                object obj = ResourceManager.GetObject("card_1_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_8 {
            get {
                object obj = ResourceManager.GetObject("card_1_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_1_9 {
            get {
                object obj = ResourceManager.GetObject("card_1_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_1 {
            get {
                object obj = ResourceManager.GetObject("card_2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_10 {
            get {
                object obj = ResourceManager.GetObject("card_2_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_11 {
            get {
                object obj = ResourceManager.GetObject("card_2_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_12 {
            get {
                object obj = ResourceManager.GetObject("card_2_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_13 {
            get {
                object obj = ResourceManager.GetObject("card_2_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_2 {
            get {
                object obj = ResourceManager.GetObject("card_2_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_3 {
            get {
                object obj = ResourceManager.GetObject("card_2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_4 {
            get {
                object obj = ResourceManager.GetObject("card_2_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_5 {
            get {
                object obj = ResourceManager.GetObject("card_2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_6 {
            get {
                object obj = ResourceManager.GetObject("card_2_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_7 {
            get {
                object obj = ResourceManager.GetObject("card_2_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_8 {
            get {
                object obj = ResourceManager.GetObject("card_2_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_2_9 {
            get {
                object obj = ResourceManager.GetObject("card_2_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_1 {
            get {
                object obj = ResourceManager.GetObject("card_3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_10 {
            get {
                object obj = ResourceManager.GetObject("card_3_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_11 {
            get {
                object obj = ResourceManager.GetObject("card_3_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_12 {
            get {
                object obj = ResourceManager.GetObject("card_3_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_13 {
            get {
                object obj = ResourceManager.GetObject("card_3_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_2 {
            get {
                object obj = ResourceManager.GetObject("card_3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_3 {
            get {
                object obj = ResourceManager.GetObject("card_3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_4 {
            get {
                object obj = ResourceManager.GetObject("card_3_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_5 {
            get {
                object obj = ResourceManager.GetObject("card_3_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_6 {
            get {
                object obj = ResourceManager.GetObject("card_3_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_7 {
            get {
                object obj = ResourceManager.GetObject("card_3_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_8 {
            get {
                object obj = ResourceManager.GetObject("card_3_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_3_9 {
            get {
                object obj = ResourceManager.GetObject("card_3_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap card_back {
            get {
                object obj = ResourceManager.GetObject("card_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Required.
        /// </summary>
        internal static string ConfirmCaption {
            get {
                return ResourceManager.GetString("ConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete your save file?
        ///All data will be lost permanently..
        /// </summary>
        internal static string ConfirmDeleteSaveFileQuestion {
            get {
                return ResourceManager.GetString("ConfirmDeleteSaveFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to end the game? 
        ///As a penalty, half your bet will be retained by the dealer..
        /// </summary>
        internal static string ConfirmEndGameQuestion {
            get {
                return ResourceManager.GetString("ConfirmEndGameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the previously saved game state. Data will be lost.
        ///
        ///Do you wish to try again?.
        /// </summary>
        internal static string ConfirmRetryLoadQuestion {
            get {
                return ResourceManager.GetString("ConfirmRetryLoadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the game state. Data will be lost.
        ///
        ///Do you wish to try again?.
        /// </summary>
        internal static string ConfirmRetrySaveQuestion {
            get {
                return ResourceManager.GetString("ConfirmRetrySaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        internal static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Required Fields.
        /// </summary>
        internal static string ErrorValidationCaption {
            get {
                return ResourceManager.GetString("ErrorValidationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; field is required..
        /// </summary>
        internal static string ErrorValidationRequiredField {
            get {
                return ResourceManager.GetString("ErrorValidationRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string InfoAboutCaption {
            get {
                return ResourceManager.GetString("InfoAboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Blackjack!
        ///
        ///In this desktop game, you can play Blackjack against the dealer 
        ///and test your luck by beating the odds.
        ///
        ///The dealer uses one deck containing 52 card 
        ///that are shuffled using the Fisher-Yates method.
        ///
        ///If you end up losing all your money, you can always trade your statistics and use the &apos;Reset Save&apos; button on the menu to get another chance to succeed.
        ///
        ///----------------------------------------------------------------------
        ///
        ///Developer : Cédric-Antoine Ouellet (cedricao)
        ///Fram [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoAboutText {
            get {
                return ResourceManager.GetString("InfoAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InfoCaption {
            get {
                return ResourceManager.GetString("InfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dealer bust!
        /// You win {0}$ .
        /// </summary>
        internal static string InfoDealerBust {
            get {
                return ResourceManager.GetString("InfoDealerBust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dealer wins!.
        /// </summary>
        internal static string InfoDealerWin {
            get {
                return ResourceManager.GetString("InfoDealerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bust. 
        ///The dealer wins!
        ///
        ///The dealer&apos;s next card would have been a
        ///{0}..
        /// </summary>
        internal static string InfoPlayerBust {
            get {
                return ResourceManager.GetString("InfoPlayerBust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win {0}$.
        /// </summary>
        internal static string InfoPlayerWin {
            get {
                return ResourceManager.GetString("InfoPlayerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie!
        ///You get {0}$ back.
        /// </summary>
        internal static string InfoTie {
            get {
                return ResourceManager.GetString("InfoTie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sfx_bet {
            get {
                return ResourceManager.GetStream("sfx_bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sfx_button_click {
            get {
                return ResourceManager.GetStream("sfx_button_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sfx_card {
            get {
                return ResourceManager.GetStream("sfx_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sfx_exit {
            get {
                return ResourceManager.GetStream("sfx_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sfx_lose {
            get {
                return ResourceManager.GetStream("sfx_lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sfx_shuffle {
            get {
                return ResourceManager.GetStream("sfx_shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sfx_tie {
            get {
                return ResourceManager.GetStream("sfx_tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sfx_win {
            get {
                return ResourceManager.GetStream("sfx_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display information about this application.
        /// </summary>
        internal static string TooltipAbout {
            get {
                return ResourceManager.GetString("TooltipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 1$ to your bet.
        /// </summary>
        internal static string TooltipBet1 {
            get {
                return ResourceManager.GetString("TooltipBet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 100$ to your bet.
        /// </summary>
        internal static string TooltipBet100 {
            get {
                return ResourceManager.GetString("TooltipBet100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 25$ to your bet.
        /// </summary>
        internal static string TooltipBet25 {
            get {
                return ResourceManager.GetString("TooltipBet25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 5$ to your bet.
        /// </summary>
        internal static string TooltipBet5 {
            get {
                return ResourceManager.GetString("TooltipBet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 50$ to your bet.
        /// </summary>
        internal static string TooltipBet50 {
            get {
                return ResourceManager.GetString("TooltipBet50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 500$ to your bet.
        /// </summary>
        internal static string TooltipBet500 {
            get {
                return ResourceManager.GetString("TooltipBet500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your bets and start the game.
        /// </summary>
        internal static string TooltipDeal {
            get {
                return ResourceManager.GetString("TooltipDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double your bet to test your luck.
        /// </summary>
        internal static string TooltipDouble {
            get {
                return ResourceManager.GetString("TooltipDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End the match and exit the game screen.
        /// </summary>
        internal static string TooltipExit {
            get {
                return ResourceManager.GetString("TooltipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get another card dealt to you.
        /// </summary>
        internal static string TooltipHit {
            get {
                return ResourceManager.GetString("TooltipHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your bet to zero.
        /// </summary>
        internal static string TooltipResetBet {
            get {
                return ResourceManager.GetString("TooltipResetBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets your entire game save.
        ///You will need to perform this action if your bank is empty..
        /// </summary>
        internal static string TooltipResetSave {
            get {
                return ResourceManager.GetString("TooltipResetSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try your luck with the cards you were dealt.
        /// </summary>
        internal static string TooltipStand {
            get {
                return ResourceManager.GetString("TooltipStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the game screen.
        /// </summary>
        internal static string TooltipStart {
            get {
                return ResourceManager.GetString("TooltipStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your previous save file is associated to a version that is no longer compatible.
        ///Therefore, it will be deleted and all associated data will be lost permanently.
        ///
        ///We are truly sorry for this inconvenience..
        /// </summary>
        internal static string WarningIncompatibleVersionSaveFile {
            get {
                return ResourceManager.GetString("WarningIncompatibleVersionSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough money to purchase this!.
        /// </summary>
        internal static string WarningInsufficientBank {
            get {
                return ResourceManager.GetString("WarningInsufficientBank", resourceCulture);
            }
        }
    }
}
